#!/bin/bash

zz=$1

echo -e "\nzone \"${zz}.steven-dujardin.sb.uclllabs.be\" {\ntype master;\nfile \"/etc/bind/db.${zz}.steven-dujardin.sb.uclllabs.be\";\n};" >> /etc/bind/named.conf.mrt-zones

echo 'Entry created in mrt-zones'

echo -e "\$TTL 300\n
@	IN	SOA	ns.steven-dujardin.sb.uclllabs.be. root.steven-dujardin.sb.uclllabs.be. (\n
				1	; Serial
				300	; Refresh
				300	; Retry
				300	; Expire
				300 ) ;  Negative Cache TTL

;name servers
@	IN	NS 	ns.steven-dujardin.sb.uclllabs.be.
@	IN	A	193.191.177.234

" >> /etc/bind/db.${zz}.steven-dujardin.sb.uclllabs.be

echo "${zz}	IN	NS	ns.steven-dujardin.sb.uclllabs.be." >> /etc/bind/db.steven-dujardin.sb.uclllabs.be

echo 'SOA record added'

serialline=$(grep "Serial" /etc/bind/db.steven-dujardin.sb.uclllabs.be)
serialnumber=$(cat /etc/bind/db.steven-dujardin.sb.uclllabs.be | grep -P 'Serial' | grep -P [0-9] |grep -o -E '[0-9]+');
newSerial=$(($serialnumber + 1))
sed -i "s/$serialnumber ; Serial/$newSerial ; Serial/" /etc/bind/db.steven-dujardin.sb.uclllabs.be

#sed -i "s/$serialnumber\t\t;\sSerial/$newSerial\t\t; Serial/" /etc/bind/db.steven-dujardin.sb.uclllabs.be
echo $newSerial;
echo -e "serial updated, restarting bind9"
chown bind:bind /etc/bind/db.${zz}.steven-dujardin.sb.uclllabs.be
echo 'Finished'

systemctl restart named

